disabled_rules:
- identifier_name
- cyclomatic_complexity

trailing_comma:
  mandatory_comma: true

included:
- macos/WebViewHost/WebViewHost
excluded:
- build
- .build
- SourcePackages
- DerivedData
- Pods
